### ISSUE TITLE
Cannot configure default user with Alpine.exe

### ISSUE THREAD

**Issue by jimorc** [yuk7/WSL-DistroLauncher#10]
I downloaded the Alpine.zip file, extracted it, and ran Alpine to register with WSL. I ran Alpine again to start it up and created a new user called jim.

When I exit, and then run
Alpine config --default-user jim
I get 

ERROR:Invalid Argument.
Failed to detect user.

If I replace Alpine.exe with Launcher.exe (see issue #9 for reason), Launcher hangs (never terminates nor produces any output).

If I start Alpine or Launcher again, I am able to su jim, so the user does exist.

**Comment by jimorc** [comment]
Alpine config -default-uid 1000
does work.

**Comment by yuk7** [comment]
@jimorc 
I confirmed same problem and `run {commands}` does not work...
Probably,Excuting internal commands requires bash.
Please retry after `apk update && apk add bash` in Alpine's shell.
Thank you your reporting!

**Comment by yuk7** [comment]
I created new issue to [AlpineWSL](https://github.com/yuk7/AlpineWSL) repository.
I'll close this issue.
