### ISSUE TITLE
docs for building launcher

### ISSUE THREAD

**Issue by Trophime** [yuk7/WSL-DistroLauncher#11]
Hi,
it would be great to have some more docs
about how to build a launcher from `main.c` .

Best

**Comment by Biswa96** [comment]
You can complie it with any Windows compiler like gcc in mingw-w64 or in cygwin. Or cl.exe in visual studio.

**Comment by yuk7** [comment]
Thank you for suggestion.
but Microsoft's official WSL-DistroLauncher was released.
https://github.com/Microsoft/WSL-DistroLauncher (can build with VisualStudio,Windows SDK)
I think no longer need this project.

This project will be discontinued...

**Comment by Biswa96** [comment]
Microsoft project is more complex (with class in C++) than yours. Simple user and novice programmer like me may preffer your simple approach. Also your code can be compiled with gcc in mingw or cygwin.

**Comment by yuk7** [comment]
Ok,I added build instruction to README.
