### ISSUE TITLE
Official WSL-DistroLauncher released

### ISSUE THREAD

**Issue by yuk7** [yuk7/WSL-DistroLauncher#12]
Official WSL-DistroLauncher was released.
https://github.com/Microsoft/WSL-DistroLauncher
I think no longer need this project.

**Comment by yuk7** [comment]
I'll create Microsoft's DistroLauncher fork.
* use exe name to instance name
* add some commands

**Comment by bentterp** [comment]
Disagree, even now I think your solution is better!

**Comment by yuk7** [comment]
As persuaded by several people, I decided to keep the project in current policy.
I also use this software, so I want to maintain it.
Thanks.
