### ISSUE TITLE
[CentOS] HRESULT:0x80004001

### ISSUE THREAD

**Issue by m-garrido** [yuk7/WSL-DistroLauncher#13]
Hello,

First of all, thanks for your tool.
I've tested to create a CentOS7 instance.
When i launch "centos.exe", i get this error:

```
Installing...
ERROR:Installation Failed!
HRESULT:0x80004001
```

For the rootfs, i've got it from the official dockerhub centos repository.
They give a ".tar.xz" file that i've conveted to ".tar.gz"
Can you give some help please?

**Comment by Biswa96** [comment]
Did you use `--hard-dereference` option in `tar -czf` command at the time of making the .tar.gz file?

**Comment by yuk7** [comment]
please use `sudo tar --zcpf ../rootfs.tar.gz *` for create tar.gz...

**Comment by Line117** [comment]
> First of all, thanks for your tool.
> I've tested to create a CentOS7 instance.
> When i launch "centos.exe", i get this error:

I got this error too, when I installed Alpine.
Run the first time exe as an administrator.
Try it.
