### ISSUE TITLE
Not an issue: Some improvements needed

### ISSUE THREAD

**Issue by Biswa96** [yuk7/WSL-DistroLauncher#3]
Recently, I am following your repo and also added some idea in my repo. But I have some suggestions, may be that help this project.

1. In newer version of Windows SDK, Microsoft has added `Wslapi.h` header file. So that you have not to make definition of that WSL functions. 2. Also you may skip to launch WSL.exe in your program by calling the [`WslLaunchInteractive`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826869(v=vs.85).aspx) function. 3. It will be easy if there is a separate header file and .c files for each of the functions.

Also many more....

**Comment by yuk7** [comment]
Thank you your suggestions.

I'm thinking like this:
1. I can't use Windows SDK's WslApi.h as is,because I use mingw-w64 compiler...
2. I already replaced the Interactive mode to `WslLaunchInteractive` function (ee8f6f0).
config --default-user is using stdout,I'm planning to use `WslLaunch` function.
3. I'll try to separate typedef to header. thanks:)

**Comment by Biswa96** [comment]
Suggestions::
1. Add commandline options to choose any file name of .tar.gz file. 
2. You may make a header file from [WSL functions](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826874(v=vs.85).aspx) website. 
3. See [LxRunOffline wiki](https://github.com/DDoSolitary/LxRunOffline/wiki) where I write how to installs other distros. Also you may contribute there. 👌

**Comment by yuk7** [comment]
@Biswa96 
1. I added tgz option at 93f513e
2. I creared wsld.h ,but not defined WSL_FLAGS yet.
3. Thank you for info. But, I don't try CentOS and Mageia,etc on WSL yet.
I tested Alpine,but that is irregular way.
and I don't have any info to write for wiki,sorry. σ)>ω<*)

**Comment by Biswa96** [comment]
BTW, if I use `#include <wslapi.h>` from SDK in Visual Studio with `WslRegisterDistribution` function, it shows the linker error `unresolved external symbol`.

**Comment by npyl** [comment]
Check this out, it may help fix the "unresolved external symbol" error.

[link](https://gist.github.com/0xbadfca11/d31ba1d1543aac615f1945c6670382c7)

**Comment by Biswa96** [comment]
Thanks @npyl . I know that details. But I was thinking to run the [`WslRegisterDistribution`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826870(v=vs.85).aspx) function without calling the `LoadLibraryW(L"wslapi.dll")` function. But now I think that's not possible.
The reason behind of my thought that all the installing, uninstalling, configuring processes are done by LxssManager.dll, not the wslapi.dll. So I think if it is possible to talk directly to LxssManager service.

**Comment by Biswa96** [comment]
@yuk7 Can you include feature to add new user?

**Comment by yuk7** [comment]
@Biswa96 
No I can't.
Because commands for add users are different depending on distribution...

**Comment by Biswa96** [comment]
An idea stuck in my mind. You have used `WslLaunch` function to get user id. 
But I've seen that the executables in Appx installer (provided in Windows store) uses `WslLaunchInteractive` function to run those commands.
There is also a advantage using the latter function. You've not to write any code to manipulate handles in `WslLaunchInteractive` function.
