### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by yuk7** [yuk7/WSL-DistroLauncher#5]
* re-write codes with in better c/c++
* use WslLaunch function for get uid in set-default-user
* Separate project
* fix worst Engrish

**Comment by Biswa96** [comment]
After seeing the WSL functions definition, I think that `WslGetDistributionConfiguration` function works for getting the UID.

You may also get UID from registry `DefaultUID` value which has `0x0` for root user and `0x3e8` for normal user.

**Comment by yuk7** [comment]
@Biswa96 
I know to that. and That does not mean its.

set --default-user function is set default user from username.
and it use the return value of the id command executed in distro.
Now run id command from wsl.exe. I want replace it to use api `WSLLaunch`.

**Comment by Biswa96** [comment]
Ya, the distros from Windows store also run `/usr/bin/id -u` to set defaut user. Working on that with IDA reverse engineering.....

**Comment by Biswa96** [comment]
Yes, now I can do that. See my last commit. Use it with `adduser --force-badname UserName` command to create user. Then change registry `DefaultUid` value to dword `0x3e8` for normal user with `RegSetValueEx()`.

**Comment by Biswa96** [comment]
I think your second Todo was solved. What's about your first and last issue? 😂

**Comment by yuk7** [comment]
@Biswa96 
haha...
Yes,Second TODO was solved.
Other issue...is not important😆
I'll close,thanks!w

**Comment by Biswa96** [comment]
Why did you released Arch and Alpine in your repo? User can download those from their original websites.

**Comment by yuk7** [comment]
@Biswa96 
That is a personal reason.
I wanted to be able to use distros on WSL immediately without using a original Linux computer.

ArchWSL has some additional basic packages. Includes patched package (glibc,fakeroot).

**Comment by Biswa96** [comment]
How about debian? Can you release a debian tar.gz file with travis-ci? Here is the shell script: https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh

**Comment by Biswa96** [comment]
There are new distros available. I've found procedure for Debian and Kali. Do you want to make new releases with those?
