### ISSUE TITLE
Alpine.exe does not have clean or help commands

### ISSUE THREAD

**Issue by jimorc** [yuk7/WSL-DistroLauncher#9]
The Alpine.exe file in .../releases/downloads/17112101/Alpine.zip does not recognize either clean or help as commands.

A workaround is to download the latest Launcher.exe and rename it as Alpine.exe.

**Comment by yuk7** [comment]
@jimorc 
Sorry to leave Alpine prebuilt image outdated...

I created new repo [yuk7/AlpineWSL](https://github.com/yuk7/AlpineWSL).
with newest launcher and rootfs.
Thank you for your testing!
